### ISSUE TITLE
duplicated examples

### ISSUE THREAD

**Issue by NLZ** [CupNoodles27/DRG-Tips-and-Tricks#1]
1. The two examples here for RJ250 double jump is duplicated:

https://github.com/CupNoodles27/DRG-Tips-and-Tricks/blob/35043c78823dc1ba6bfac3593c6cbe9a2429d857/README.md?plain=1#L527

2. This is also a duplicate of
https://github.com/CupNoodles27/DRG-Tips-and-Tricks/blob/35043c78823dc1ba6bfac3593c6cbe9a2429d857/README.md?plain=1#L793
this
https://github.com/CupNoodles27/DRG-Tips-and-Tricks/blob/35043c78823dc1ba6bfac3593c6cbe9a2429d857/README.md?plain=1#L722

**Comment by CupNoodles27** [comment]
Thanks, fixed the RJ one. The drop pod video is intended to be a duplicate, at 0:25 in that video you can see the scout pull out his weapon and start moving around.
